// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package helper_db_test

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockITransactionBundler creates a new instance of MockITransactionBundler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockITransactionBundler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockITransactionBundler {
	mock := &MockITransactionBundler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockITransactionBundler is an autogenerated mock type for the ITransactionBundler type
type MockITransactionBundler struct {
	mock.Mock
}

type MockITransactionBundler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockITransactionBundler) EXPECT() *MockITransactionBundler_Expecter {
	return &MockITransactionBundler_Expecter{mock: &_m.Mock}
}

// WithTransaction provides a mock function for the type MockITransactionBundler
func (_mock *MockITransactionBundler) WithTransaction(ctx context.Context, fn func(ctx context.Context) error) error {
	ret := _mock.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for WithTransaction")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(ctx context.Context) error) error); ok {
		r0 = returnFunc(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockITransactionBundler_WithTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTransaction'
type MockITransactionBundler_WithTransaction_Call struct {
	*mock.Call
}

// WithTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(ctx context.Context) error
func (_e *MockITransactionBundler_Expecter) WithTransaction(ctx interface{}, fn interface{}) *MockITransactionBundler_WithTransaction_Call {
	return &MockITransactionBundler_WithTransaction_Call{Call: _e.mock.On("WithTransaction", ctx, fn)}
}

func (_c *MockITransactionBundler_WithTransaction_Call) Run(run func(ctx context.Context, fn func(ctx context.Context) error)) *MockITransactionBundler_WithTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(ctx context.Context) error
		if args[1] != nil {
			arg1 = args[1].(func(ctx context.Context) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockITransactionBundler_WithTransaction_Call) Return(err error) *MockITransactionBundler_WithTransaction_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockITransactionBundler_WithTransaction_Call) RunAndReturn(run func(ctx context.Context, fn func(ctx context.Context) error) error) *MockITransactionBundler_WithTransaction_Call {
	_c.Call.Return(run)
	return _c
}
